package com.cargosphere.audit.entity.enums;

public enum AuditAction {

    USER_REGISTERED,
    USER_LOGIN,
    USER_LOGIN_FAILED,

    SHIPMENT_CREATED,
    SHIPMENT_UPDATED,
    SHIPMENT_STATUS_UPDATED,

    CONTAINER_ALLOCATED,
    CONTAINER_RELEASED,

    DOCUMENT_CREATED,
    DOCUMENT_VERIFIED,
    DOCUMENT_REJECTED,

    PAYMENT_CREATED,
    PAYMENT_STATUS_UPDATED,
    PAYMENT_COMPLETED,
    PAYMENT_REFUNDED
}