package com.cargosphere.shipment.entity.enums;

public enum ShipmentEventType {
    CREATED,
    CARGO_ADDED,
    BOOKED,
    PICKED_UP,
    DEPARTED,
    IN_TRANSIT,
    ARRIVED,
    OUT_FOR_DELIVERY,
    DELIVERED,
    CANCELLED,
    DELAYED,
    CONTAINER_ALLOCATED,
    ADMIN_PROCESSING_STARTED,
    CARGO_VERIFIED,
    DOCUMENTS_VERIFIED,
    PAYMENT_CONFIRMED,
    EBILL_GENERATED
}