package com.cargosphere.shipment.service.support;

import com.cargosphere.shipment.dto.ebill.snapshot.EbillSnapshot;
import org.apache.pdfbox.Loader;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.Arrays;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class EbillPdfGeneratorTest {

    private EbillPdfGenerator generator;

    @BeforeEach
    void setUp() {
        generator = new EbillPdfGenerator();
    }

    @Test
    void shouldGenerateValidPdfFromImmutableSnapshot()
            throws Exception {
        OffsetDateTime generatedAt =
                OffsetDateTime.of(
                        2026,
                        8,
                        3,
                        10,
                        0,
                        0,
                        0,
                        ZoneOffset.UTC
                );

        EbillSnapshot snapshot =
                new EbillSnapshot(
                        "1.0",
                        "EBL-20260803-A1B2C3D4",
                        1,
                        generatedAt,
                        5L,
                        null,
                        null,
                        List.of(),
                        List.of(),
                        List.of(),
                        List.of(),
                        List.of(),
                        List.of(),
                        null
                );

        byte[] pdfBytes =
                generator.generate(snapshot);

        String sampleOutput =
                System.getProperty("ebill.sample.output");
        if (sampleOutput != null) {
            Path outputPath = Path.of(sampleOutput);
            Files.createDirectories(outputPath.getParent());
            Files.write(outputPath, pdfBytes);
        }

        assertThat(pdfBytes).isNotEmpty();

        String header =
                new String(
                        Arrays.copyOfRange(
                                pdfBytes,
                                0,
                                5
                        ),
                        StandardCharsets.US_ASCII
                );

        assertThat(header).isEqualTo("%PDF-");

        try (
                PDDocument document =
                        Loader.loadPDF(pdfBytes)
        ) {
            assertThat(document.getNumberOfPages())
                    .isGreaterThanOrEqualTo(1);

            assertThat(
                    document
                            .getDocumentInformation()
                            .getTitle()
            ).isEqualTo(
                    "CargoSphere eBill "
                            + "EBL-20260803-A1B2C3D4"
            );

            String text =
                    new PDFTextStripper()
                            .getText(document);

            assertThat(text)
                    .contains("CARGOSPHERE")
                    .contains("ELECTRONIC BILL OF LADING")
                    .contains("EBL-20260803-A1B2C3D4")
                    .contains("Version 1")
                    .contains("Generated by admin 5")
                    .contains("SHIPMENT INFORMATION")
                    .contains("PAYMENT DETAILS")
                    .contains("DOCUMENT DECLARATION");
        }
    }

    @Test
    void shouldRejectNullSnapshot() {
        assertThatThrownBy(() ->
                generator.generate(null)
        )
                .isInstanceOf(
                        IllegalArgumentException.class
                )
                .hasMessage(
                        "eBill snapshot must not be null"
                );
    }
}
