package com.cargosphere.shipment.service.support;

import com.cargosphere.shipment.dto.ebill.snapshot.EbillSnapshot;
import com.cargosphere.shipment.exception.EbillPdfGenerationException;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDDocumentInformation;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDFont;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;
import java.io.IOException;

@Component
public class EbillPdfGenerator {

    private static final float LEFT_MARGIN = 50F;
    private static final float TITLE_Y = 790F;
    private static final float FIRST_LINE_Y = 745F;
    private static final float LINE_GAP = 24F;

    public byte[] generate(
            EbillSnapshot snapshot
    ) {
        if (snapshot == null) {
            throw new IllegalArgumentException(
                    "eBill snapshot must not be null"
            );
        }

        try (
                PDDocument document = new PDDocument();
                ByteArrayOutputStream outputStream =
                        new ByteArrayOutputStream()
        ) {
            PDPage page = new PDPage(PDRectangle.A4);
            document.addPage(page);

            PDFont titleFont =
                    new PDType1Font(
                            Standard14Fonts.FontName
                                    .HELVETICA_BOLD
                    );

            PDFont bodyFont =
                    new PDType1Font(
                            Standard14Fonts.FontName
                                    .HELVETICA
                    );

            configureDocumentInformation(
                    document,
                    snapshot
            );

            try (
                    PDPageContentStream contentStream =
                            new PDPageContentStream(
                                    document,
                                    page
                            )
            ) {
                writeLine(
                        contentStream,
                        titleFont,
                        20F,
                        TITLE_Y,
                        "CargoSphere eBill"
                );

                writeLine(
                        contentStream,
                        bodyFont,
                        12F,
                        FIRST_LINE_Y,
                        "eBill Number: "
                                + printable(
                                        snapshot.ebillNumber()
                                )
                );

                writeLine(
                        contentStream,
                        bodyFont,
                        12F,
                        FIRST_LINE_Y - LINE_GAP,
                        "Version: "
                                + printable(
                                        snapshot.ebillVersion()
                                )
                );

                writeLine(
                        contentStream,
                        bodyFont,
                        12F,
                        FIRST_LINE_Y - (LINE_GAP * 2),
                        "Generated At: "
                                + printable(
                                        snapshot.generatedAt()
                                )
                );

                writeLine(
                        contentStream,
                        bodyFont,
                        12F,
                        FIRST_LINE_Y - (LINE_GAP * 3),
                        "Generated By: "
                                + printable(
                                        snapshot.generatedBy()
                                )
                );

                writeLine(
                        contentStream,
                        bodyFont,
                        12F,
                        FIRST_LINE_Y - (LINE_GAP * 4),
                        "Snapshot Schema: "
                                + printable(
                                        snapshot.schemaVersion()
                                )
                );
            }

            document.save(outputStream);
            return outputStream.toByteArray();
        } catch (IOException exception) {
            throw new EbillPdfGenerationException(
                    "Failed to generate eBill PDF",
                    exception
            );
        }
    }

    private void configureDocumentInformation(
            PDDocument document,
            EbillSnapshot snapshot
    ) {
        PDDocumentInformation information =
                new PDDocumentInformation();

        information.setTitle(
                "CargoSphere eBill "
                        + printable(snapshot.ebillNumber())
        );

        information.setAuthor("CargoSphere");
        information.setSubject(
                "Immutable electronic shipment bill"
        );

        document.setDocumentInformation(information);
    }

    private void writeLine(
            PDPageContentStream contentStream,
            PDFont font,
            float fontSize,
            float yPosition,
            String text
    ) throws IOException {
        contentStream.beginText();
        contentStream.setFont(font, fontSize);
        contentStream.newLineAtOffset(
                LEFT_MARGIN,
                yPosition
        );
        contentStream.showText(printable(text));
        contentStream.endText();
    }

    private String printable(
            Object value
    ) {
        if (value == null) {
            return "N/A";
        }

        return value.toString()
                .replaceAll(
                        "[^\\x20-\\x7E]",
                        "?"
                );
    }
}
